In [ ]:
# first we  draw a subset of data from large dataset,because i am training my nn on cpu
# work flow of ANN
# we start with data loader objects
# then training pipeline
# then evaluation

In [ ]:
# importing required libraries
import pandas as pd # pandas for preprocessing and data analysis
import torch # pytorch
from sklearn.model_selection import train_test_split # to split data into training and test data
import matplotlib.pyplot as plt # for visualizations
import torch.nn as nn # neural network module of pytorch
from torch.utils.data import Dataset,DataLoader # to load data and make batches of features and labels
import torch.optim as optim # optimizer fro parameter updates
import numpy as np # for numerical calculation

In [ ]:
# Cheking GPU availability ,step 1 for training on gpu
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f' using device:{device}')

 using device:cuda

In [ ]:
# setting random seed for reproducibility
torch.manual_seed(42)

In [ ]:
# load data
df = pd.read_csv('/content/fashion-mnist_train.csv')
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# separating features from target labels
x= df.drop(columns='label',axis=1)
y=df['label']

In [ ]:
x

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,5,0,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,1,2,0,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,0,0,0,0,0,0,0,0,0,0,...,73,0,0,0,0,0,0,0,0,0
59997,0,0,0,0,0,0,0,0,0,0,...,160,162,163,135,94,0,0,0,0,0
59998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y

0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64

In [ ]:
# spliting data into train,test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
# scaling the features between 0 and 1 range of values for stability
x_train = x_train/255.0
x_test = x_test/255.0

In [ ]:
x_train

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
48572,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
38696,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
13611,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
35213,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
31766,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.003922,0.0,...,0.000000,0.000000,0.003922,0.000000,0.043137,0.145098,0.023529,0.000000,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54343,0.0,0.0,0.0,0.0,0.0,0.011765,0.027451,0.000000,0.000000,0.0,...,0.682353,0.705882,0.768627,0.921569,0.000000,0.000000,1.000000,0.898039,0.65098,0.0
38158,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
860,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.003922,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
15795,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.007843,0.000000,0.0,...,0.368627,0.290196,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0
56422,0.0,0.0,0.0,0.0,0.0,0.000000,0.360784,0.807843,0.462745,0.0,...,0.129412,0.082353,0.011765,0.000000,0.309804,0.000000,0.000000,0.003922,0.00000,0.0

In [ ]:
print(type(x_train))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# our  tain,test split or dataframe type, pytorch expects tensors
# converting df type to numpy array and then numpy array to tensor
x_train = x_train.values
x_test = x_test.values
y_train = y_train.values
y_test = y_test.values

In [ ]:
print(type(x_train))

<class 'numpy.ndarray'>

In [ ]:
# converting now np arrays to tensors
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [ ]:
x_train

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0039, 0.0000, 0.0000]],
       dtype=torch.float64)

In [ ]:
# creating custom dataset class
class CustomDataset(Dataset): # our custom class inherit base Dataset class
     def __init__(self,features,labels):
       self.features = torch.tensor(features,dtype=torch.float32).reshape(-1,1,28,28) #since we haive 784 columns/features,this dataset class will fetch row that is 1 dimensional,now we are working on images that are 2  dimensional, so reshaping as 28*28 makes 784 columns total,28 pixels left to right,28 pixels 28 pixels top to bottom, and 1 represent its 1 channel/gray scale image
       self.labels = torch.tensor(labels, dtype=torch.long) # attribute to store labels
      # pytorch expects features in float dtype and labels in long dtype means integers
     def __len__(self):
      return self.features.shape[0] # no. of rows
     def __getitem__(self,index):
      return self.features[index], self.labels[index] # return rows and  labels at provided index

In [ ]:
# creating train and test objects of custom class to load train and test data separatly from same custom class
train_dataset = CustomDataset(x_train,y_train) # arguments provided for features and labels parameters
test_dataset = CustomDataset(x_test,y_test)

/tmp/ipykernel_1556/3233297893.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.features = torch.tensor(features,dtype=torch.float32).reshape(-1,1,28,28) #since we haive 784 columns/features,this dataset class will fetch row that is 1 dimensional,now we are working on images that are 2  dimensional, so reshaping as 28*28 makes 784 columns total,28 pixels left to right,28 pixels 28 pixels top to bottom, and 1 represent its 1 channel/gray scale image
/tmp/ipykernel_1556/3233297893.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.labels = torch.tensor(labels, dtype=torch.long) # attribute to store labels

In [ ]:
# cheking no. of rows by calling len method of custom class
len(train_dataset)

48000

In [ ]:
# extracting rows by calling get item method of custom class
train_dataset[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2275,
           0.5333, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0078, 0.0078, 0.0275, 0.0078, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0275, 0.2157, 0.3137, 0.4235, 0.5922,
           1.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0078, 0.0078, 0.0196, 0.0000, 0.0078, 0.0078, 0.0471,
           0.2863, 0.4039, 0.5137, 0.5608, 0.5608, 0.6902, 0.6314, 0.3333,
           0.3843, 0.0980, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0078, 0.0000, 0.0588, 0.4235, 0.5216, 0.5608,
           0.7412, 0.7686, 0.7686, 0.7020, 0.4431, 0.3059, 0.1255, 0.0000,
           0.2078, 0.4431, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0196, 0.0000, 0.0471, 0.1843, 0.1569, 0.1843,
           0.0588, 0.0000, 0.0000, 0.0784, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0078, 0.7608, 0.2157, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0078, 0.0275, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000,
           0.0078, 0.7882, 0.6314, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0000, 0.0078, 0.0078,
           0.0196, 0.0000, 0.0000, 0.0000, 0.0078, 0.0078, 0.0000, 0.0000,
           0.1059, 0.8000, 0.6510, 0.0588],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0078, 0.0078, 0.0000, 0.0196, 0.0078, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0078, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.3922, 0.8196, 0.5804, 0.1373],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0078, 0.0196, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0196, 0.0078, 0.0000, 0.0078, 0.0000, 0.0000,
           0.6706, 0.8902, 0.1961, 0.1647],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0980,
           0.9765, 0.5137, 0.1765, 0.3137],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0667, 0.2667,
           0.4157, 0.2353, 0.3451, 0.1255],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0980, 0.1843, 0.2745, 0.7490,
           0.4431, 0.0863, 0.0588, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0588, 0.0980, 0.2941, 0.6902, 0.8314, 0.4235,
           0.4824, 0.1373, 0.0863, 0.0275],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0078,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0000,
           0.0000, 0.0980, 0.2863, 0.5804, 0.8196, 0.1647, 0.0000, 0.0000,
           0.1255, 0.4627, 0.0196, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0667, 0.3255, 0.6118, 0.5922, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0078, 0.6235, 0.1961, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000, 0.0196,
           0.3451, 0.6824, 0.4235, 0.0000, 0.0000, 0.0078, 0.0000, 0.0000,
           0.0000, 0.8196, 0.2863, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1059, 0.0667, 0.4627,
           0.2157, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1961,
           0.6627, 0.4627, 0.0000, 0.0000, 0.0275, 0.0000, 0.0000, 0.0000,
           0.0000, 0.6627, 0.3137, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0471, 0.2078, 0.0392, 0.3059,
           0.6039, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0863, 0.8000,
           0.5333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000,
           0.0000, 0.6902, 0.4157, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0078, 0.0275, 0.0000, 0.0275, 0.0196,
           0.6431, 0.0078, 0.0000, 0.0000, 0.0000, 0.2941, 0.5725, 0.7490,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078, 0.0000,
           0.0000, 0.7294, 0.4824, 0.0000],
          [0.1176, 0.2353, 0.0980, 0.1059, 0.2667, 0.3255, 0.1843, 0.2078,
           0.3725, 0.1765, 0.0000, 0.0784, 0.4627, 0.6627, 0.6235, 0.0000,
           0.0000, 0.0078, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.6627, 0.3333, 0.0000],
          [0.1059, 0.4627, 0.5216, 0.4745, 0.3922, 0.5412, 0.2941, 0.3137,
           0.2863, 0.4745, 0.5412, 0.5412, 0.6824, 0.6314, 0.0078, 0.0000,
           0.0196, 0.0078, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0078,
           0.0000, 0.6235, 0.5608, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0196, 0.1176, 0.2078, 0.1961, 0.3137,
           0.2549, 0.4157, 0.5137, 0.1961, 0.2275, 0.0000, 0.0000, 0.0000,
           0.0078, 0.0275, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.5529, 0.5804, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000]]]),
 tensor(5))

In [ ]:
# creating train and test loader objects of DataLoader class
train_loader = DataLoader(train_dataset,batch_size= 128,shuffle= True,pin_memory= True)
test_loader = DataLoader(test_dataset,batch_size=128, shuffle= False, pin_memory= True) # we dont need to shuffle data in evaluation,beacuese it effect accuracies

In [ ]:
# defining neural network class
class Model(nn.Module): # our custom class inherit base nn module class to access its offerings
     def __init__(self,input_features): # we need no. of columns as input,to initialize code
       super().__init__()
       self.feature_extraction_layer = nn.Sequential(
      # first conv-pool layers pair
      nn.Conv2d(input_features,32,kernel_size=3,padding='same'), # input feature represents input channels as rgb/or grayscale,we provide values as 1 or 3,then output channels, means no. filters used in conv layer,expample 64 filters means 54 types of patterns, 1 filter detect 1 pattern,same padding means same size of output as = input, 0 padding so size after padding will be same, 3 means 3 by 3 kernal
      nn.ReLU(),
      nn.BatchNorm2d(32), # batch normalization on activation before passing to 2nd layer, 32 filters maps/output channels on which it is applied
      nn.MaxPool2d(kernel_size=2,stride=2), # kernal is 2 by 2 and stride/jump of 2
      #2nd conv-pool pair layer
      nn.Conv2d(32,64,kernel_size=3,padding='same'),# here input features/channel will be the output of previous layer, and output channels are 64 filters to be used to detect 64 types of patterns
      nn.ReLU(),
      nn.BatchNorm2d(64),
      nn.MaxPool2d(kernel_size=2,stride=2)

      # filters are feature maps from convolutional layers before passing to max pool layer to reduce dimension
      )
       self.classification_layer = nn.Sequential(
           # first we will used flatten layer to flatten tensor from convolutional layer
           nn.Flatten(),
           # hidden layer
           nn.Linear(64*7*7,128), # 64 by 7 by 7 is input dimension required for hidden layer, 128 number of neurons
           nn.ReLU(),
           nn.Dropout(p=0.4),
           nn.Linear(128,64),
           nn.ReLU(),
           nn.Dropout(p=0.4),
           nn.Linear(64,10), # output layer
           # did not pplied sigmoid because we are using cross entropy loss that internally uses sigmoid to convert classes to probabilites

           # tensor shape
           #first we use 2d image in conv layer of shape 1,28,28 where 28 by 28 pixel height and width and 1 represents gray scale image
            #  then this image is passed to 32 filters/feature maps ,so shape becomes 32,28,28 because same padding keeps shape of matrix/tensor same
             #  then pooling layer reduces dimension to half because 2 kernal size and 2 srtide,so shape becomes 32,14,14
              # then 2nd conv layer where 64 neurons passed made is 64,14,14 as shape,
               #which is then pass to wnd pool layer that half dimesnison to 64,7,7 '''
       )

     def forward(self,x):
        x= self.feature_extraction_layer(x)
        x=self.classification_layer(x)
        return x

In [ ]:
# setting learning rate and epochs
epochs = 50
learning_rate = 0.1

In [ ]:
# instansiate the model/make model object
model = Model(1) # providing no. of columns as argument to num_features parameter
model = model.to(device) # step 2 for training on GPU

In [ ]:
# loss function, its independent not used with model object
loss_function = nn.CrossEntropyLoss()

In [ ]:
# optimizer
optimizer = optim.SGD(model.parameters(),lr= learning_rate,weight_decay=1e-4) # 1e-4= 10**-4,applied l2 regularization

In [ ]:
# total batches
len(train_loader)

375

In [ ]:
# Training pipeline
# defining loop fpr each epoch
for epoch in range(epochs):
  total_epoch_loss = 0 # initialized, will help to check total loss per epoch
  # defining loop to load batches
  for batch_features , batch_labels in train_loader:
    # move data to GPU, step 3 for training model on gpu
    batch_features , batch_labels = batch_features.to(device) , batch_labels.to(device)
    # forward pass
    y_predicted = model(batch_features)
    # loss calculate
    loss = loss_function(y_predicted,batch_labels)
    # clear gradients
    optimizer.zero_grad()
    # back pass
    loss.backward()
    # parameters update
    optimizer.step()

    total_epoch_loss = total_epoch_loss + loss.item() # loss. item will convert single batch loss into scalar and add it to toal epoch loss, will run until loop end, loop will run for 150 batches
  average_loss = total_epoch_loss/len(train_loader)   # means average loss in each epoch per batch ,lentrain loder will give total no. of batches
  print(f'Epoch:{epoch + 1} , Loss: {average_loss}')

Epoch:1 , Loss: 0.589856197198232
Epoch:2 , Loss: 0.3699384552240372
Epoch:3 , Loss: 0.31253292938073474
Epoch:4 , Loss: 0.28422213153044384
Epoch:5 , Loss: 0.2563097714384397
Epoch:6 , Loss: 0.23844863563776017
Epoch:7 , Loss: 0.22098184949159622
Epoch:8 , Loss: 0.20759968930482864
Epoch:9 , Loss: 0.19111418986320497
Epoch:10 , Loss: 0.17687447424729666
Epoch:11 , Loss: 0.17081047873695693
Epoch:12 , Loss: 0.16069533478220305
Epoch:13 , Loss: 0.15495053633054098
Epoch:14 , Loss: 0.1465217173198859
Epoch:15 , Loss: 0.13550594753026962
Epoch:16 , Loss: 0.1332970088124275
Epoch:17 , Loss: 0.1274847260514895
Epoch:18 , Loss: 0.11737333485980829
Epoch:19 , Loss: 0.11195917349060376
Epoch:20 , Loss: 0.10682321666677792
Epoch:21 , Loss: 0.10285117164254189
Epoch:22 , Loss: 0.09739502387742202
Epoch:23 , Loss: 0.0957432444592317
Epoch:24 , Loss: 0.09180178135881821
Epoch:25 , Loss: 0.08385957563916842
Epoch:26 , Loss: 0.08311615334699551
Epoch:27 , Loss: 0.07913948450485865
Epoch:28 , Loss: 0.07217270389695962
Epoch:29 , Loss: 0.07403642501930396
Epoch:30 , Loss: 0.06957353537778059
Epoch:31 , Loss: 0.06979002992063761
Epoch:32 , Loss: 0.06318738103409609
Epoch:33 , Loss: 0.06160086079935233
Epoch:34 , Loss: 0.060588816331078606
Epoch:35 , Loss: 0.06340306923538447
Epoch:36 , Loss: 0.060596096590161325
Epoch:37 , Loss: 0.053478010083238284
Epoch:38 , Loss: 0.05178785857309898
Epoch:39 , Loss: 0.05291713803137342
Epoch:40 , Loss: 0.04991197013730804
Epoch:41 , Loss: 0.05061210952078303
Epoch:42 , Loss: 0.05049516918634375
Epoch:43 , Loss: 0.046315643993516765
Epoch:44 , Loss: 0.04605540114827454
Epoch:45 , Loss: 0.04563235298668345
Epoch:46 , Loss: 0.04358573491933445
Epoch:47 , Loss: 0.043266178995370864
Epoch:48 , Loss: 0.04055623832469185
Epoch:49 , Loss: 0.037897310586025315
Epoch:50 , Loss: 0.041879442383845646

In [ ]:
# set model to evaluation mode
model.eval() # tells model that we use now this model for evaluation purpose

Model(
  (feature_extraction_layer): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=same)
    (1): ReLU()
    (2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=same)
    (5): ReLU()
    (6): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classification_layer): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=3136, out_features=128, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.4, inplace=False)
    (7): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [ ]:
# evaluation
total = 0
correct = 0

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        batch_features , batch_labels = batch_features.to(device) , batch_labels.to(device)

        # forward pass
        y_predicted = model(batch_features)

        # get predicted class indices
        _, predicted = torch.max(y_predicted, 1)
        # we dont need max value,we actually need index ,the position where it lies to extract class
        # so using _, means ignore first value, return 2nd vvalue baause normally it return both max and indices

        # total samples
        total = total + batch_labels.shape[0]

        # correct predictions
        correct = correct + (predicted == batch_labels).sum().item()

accuracy=(correct / total)*100
print(f'Accuracy={accuracy}%')

Accuracy=92.38333333333333%

In [ ]:
# evaluation on training data

total = 0
correct = 0

with torch.no_grad():
    for batch_features, batch_labels in train_loader:
        batch_features , batch_labels = batch_features.to(device) , batch_labels.to(device)

        # forward pass
        y_predicted = model(batch_features)

        # get predicted class indices
        _, predicted = torch.max(y_predicted, 1)
        # we dont need max value,we actually need index ,the position where it lies to extract class
        # so using _, means ignore first value, return 2nd vvalue baause normally it return both max and indices

        # total samples
        total = total + batch_labels.shape[0]

        # correct predictions
        correct = correct + (predicted == batch_labels).sum().item()

accuracy=(correct / total)*100
print(f'Accuracy={accuracy}%')

Accuracy=99.64375%

In [ ]:
# since training accuracy is 93% and test accuracy is 83% approx,this 10% gap means ovefitting
# solution for optimization and reducing over fitting
# 1) adding more data, reduce chance of memorizing data,forced to lear patterns as the data become diverse,reduce biasness,not applicable in our case as we already used whole data
# 2) reducing complexity of neural network arcitechture,not applicable in our case as our arcitechture has only 2 layers
# 3) Regularization ,adding penalty to loss function,L1,L2,L2 is used mostly in deep learning,applicale in out case
# 4) Dropouts ,randomly shutting down few neuron of some layers,during training, applicable in our case
# 5) Data Augmentation , modifying images, tilt,flip,rotate etc, so variations, diversity increaces,better to use with cnn
# 6) Batch normalization ,to stabilize training,applicable
# 7) early stopping, stopping training early ,will not use

In [ ]:
# Dropout
# applied to hidden layers
# applied after relu activation fucntion
# randomly turns p% neurons in hidden layer during each forward pass,we set p value ,for example p=0.5 means turn off 50 % neurons
# this has regularization effect
# during evaluation,dropout is not used,

In [ ]:
# Batch normalization
# improves training stability and speed up training
# parameters keeps updating during each forward pass,we normalize inputs of each layer   between certain range of values before passing them between hidden layers, during training
# typically applies to hidden layers
# solve the problem of  internal covariate shift,means next layer keeps seeing different distributions,cause training becomes slow,network becomes unstable
# batch normalization takes activation and does measn= 0 and variance= 1,now data is centered scaled stable
# applied after hidden layer;s linear layer, ,before activation function
# includes learnable parameters like scaling,shifting
# not used during EVALUATION
# normalize activation means normalize features because 1 neuron that get weights and bias represent 1 feature/column
# distribution means centermean of datata and its spread variance

In [ ]:
# Regularization
# we add sum penalty term in loss function, so then we are focused not only minimizing loss but combination of loss and penalty term
# results in not getting high values of weights, this helps with over fitting
# applied to model wights, not on biases
# example in l2 regularization the penalty term is sum of, square of all the weights, multplied with regularization constant lambda,addedto orignal loss function
# lambda constant tells how strong regularization you want
# we can simply add loss term to gradients during back pass, this is called weights decay,
# it basically penalizes large weights,so big values of weight are distributed to other weights thus ove dependece on certain weights decreaces
# no effect on bias,only applied during training
# we are going to apply l2 regularization furing back pass to our gradients,simply weights decay

In [ ]:
df.shape

(60000, 785)